---
- hosts: localhost
  remote_user: root

  vars:
    debug_enabled_default: false

    users:
      - username: testuser101
        password: $6$/y5RGZnFaD3f$96xVdOAnldEtSxivDY02h.DwPTrJgGQl8/MTRRrFAwKTYbFymeKH/1Rxd3k.RQfpgebM6amLK3xAaycybdc.60
        update_password: on_create
        comment: Test User 100
        shell: /bin/bash
        ssh_key: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8crAHG/a9QBD4zO0ZHIjdRXy+ySKviXVCMIJ3/NMIAAzDyIsPKToUJmIApHHHF1/hBllqzBSkPEMwgFbXjyqTeVPHF8V0iq41n0kgbulJG testuser101@server1
          ssh-rsa AAAA.... testuser101@server2
        exclusive_ssh_key: yes
        use_sudo: no
        user_state: present

      - username: testuser102
        password: $6$F/KXFzMa$ZIDqtYtM6sOC3UmRntVsTcy1rnsvw.6tBquOhX7Sb26jxskXpve8l6DYsQyI1FT8N5I5cL0YkzW7bLbSCMtUw1
        update_password: always
        comment: Test User 101
        groups: testnew102
        shell: /bin/sh
        use_sudo: yes
        user_state: present

  roles:
    - ansible-role-create-users
